const ShopActionTypes= {
    FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_CULLECTION_FAILURE: 'FETCH_CULLECTION_FAILURE'
}

export default ShopActionTypes;